-- MySQL Script generated by MySQL Workbench
-- 08/11/15 17:15:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

-- -----------------------------------------------------
-- Schema piano_school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema piano_school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `piano_school` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `piano_school` ;

-- -----------------------------------------------------
-- Table `piano_school`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piano_school`.`teachers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `experience` VARCHAR(255) NULL COMMENT '',
  `degrees` VARCHAR(255) NULL COMMENT '',
  `institute` VARCHAR(255) NULL COMMENT '',
  `teacher_phone` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piano_school`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piano_school`.`students` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `level` INT NULL COMMENT '',
  `remaining_hour` INT NULL DEFAULT 0 COMMENT '',
  `student_phone` VARCHAR(45) NULL COMMENT '',
  `parent_phone` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piano_school`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piano_school`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `firstname` VARCHAR(255) NOT NULL COMMENT '',
  `lastname` VARCHAR(255) NOT NULL COMMENT '',
  `nickname` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `password` VARCHAR(60) NOT NULL COMMENT '',
  `remember_token` VARCHAR(100) NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '',
  `updated_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '',
  `approved` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `date_of_birth` DATE NOT NULL COMMENT '',
  `teachers_id` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  `students_id` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  INDEX `fk_users_teachers_idx` (`teachers_id` ASC)  COMMENT '',
  INDEX `fk_users_students1_idx` (`students_id` ASC)  COMMENT '',
  CONSTRAINT `fk_users_teachers`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `piano_school`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `piano_school`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piano_school`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piano_school`.`password_resets` (
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `token` VARCHAR(255) NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piano_school`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piano_school`.`migrations` (
  `migration` VARCHAR(255) NOT NULL COMMENT '',
  `batch` INT(11) NOT NULL COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piano_school`.`student_payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piano_school`.`student_payments` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `hours` INT NOT NULL COMMENT '',
  `students_id` INT UNSIGNED NOT NULL COMMENT '',
  `teachers_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_student_payments_students1_idx` (`students_id` ASC)  COMMENT '',
  INDEX `fk_student_payments_teachers1_idx` (`teachers_id` ASC)  COMMENT '',
  CONSTRAINT `fk_student_payments_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `piano_school`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_payments_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `piano_school`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piano_school`.`table1`
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `piano_school`.`students_teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piano_school`.`students_teachers` (
  `students_id` INT UNSIGNED NOT NULL COMMENT '',
  `teachers_id` INT UNSIGNED NOT NULL COMMENT '',
  `start_time` DATETIME NOT NULL COMMENT '',
  `end_time` DATETIME NOT NULL COMMENT '',
  `location` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`students_id`, `teachers_id`)  COMMENT '',
  INDEX `fk_students_has_teachers_teachers1_idx` (`teachers_id` ASC)  COMMENT '',
  INDEX `fk_students_has_teachers_students1_idx` (`students_id` ASC)  COMMENT '',
  CONSTRAINT `fk_students_has_teachers_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `piano_school`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_teachers_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `piano_school`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
